version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    rebase-strategy: 'disabled'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'security: '
    open-pull-requests-limit: 0 # only check security updates
