# Copyright (c) 2018 GitHub, Inc. and contributors
# Copyright 2019 Google LLC

# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.

include ../shell.mk
include ../docker.mk

IMAGE_NAME=gcloud-auth

lint: shell-lint docker-lint

build: docker-build

test: shell-test

publish: docker-publish
