name: Cloud Storage Uploader
description: Upload files or folders to GCS buckets
author: GoogleCloudPlatform

inputs:
  credentials:
    description: |-
      Optional service account key to use for authentication to GCS. This should be the JSON
      formatted private key which can be exported from the Cloud Console. The
      value can be raw or base64-encoded.
    required: false
  path:
    description: |-
      The path to a file or folder inside the action's filesystem
      that should be uploaded to the bucket.
      You can specify either the absolute path or the relative path from the action.
    required: true
  destination:
    description: |-
      GCS bucket name of form <bucketname> or with an optional prefix
      of form <bucketname>/<prefix>
    required: true

runs:
  using: "node12"
  main: "dist/index.js"
