#!/bin/sh
# Copyright (c) 2018 GitHub, Inc. and contributors
# Copyright 2019 Google LLC

# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.

# Exit if any subcommand fails
set -e

# Ensure we're always running from the project root
cd "$(dirname "$0")/.."

bats test/*.bats
shellcheck *.sh
