name: 'Deploy to Google App Engine'
description: 'Deploy to Google App Engine'
author: 'GoogleCloudPlatform'

inputs:
  project_id:
    description: 'The GCP project ID'
    require: true
  deliverables:
    description: |-
      The yaml files for the services or configurations you want to deploy.
      If not given, defaults to app.yaml in the current directory. If that is
      not found, attempts to automatically generate necessary configuration
      files (such as app.yaml) in the current directory.
    required: false
  image_url:
    description: |-
      Deploy with a specific container image. The image url must be from one of
      the valid gcr hostnames.
    required: false
  version:
    description: |-
      The version of the app that will be created or replaced by this
      deployment. If you do not specify a version, one will be generated for
      you.
    required: false
  promote:
    description: 'Promote the deployed version to receive all traffic.'
    default: true
    required: false

outputs:
  url:
    description: 'URL of your App Engine Application'

runs:
  using: node12
  main: dist/index.js
