name: deploy-cloud-functions Unit

on:
  push:
    paths:
    - 'deploy-cloud-functions/**'
    - '.github/workflows/deploy-cf**'
  pull_request:
    paths:
    - 'deploy-cloud-functions/**'
    - '.github/workflows/deploy-cf**'

jobs:
  run:
    name: test
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@master
      with:
        node-version: 12.x

    - name: npm install
      run: npm install
      working-directory: ./deploy-cloud-functions

    - name: npm lint
      run: npm run lint
      working-directory: ./deploy-cloud-functions

    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_email: ${{ secrets.DEPLOY_CF_SA_EMAIL }}
        service_account_key: ${{ secrets.DEPLOY_CF_SA_KEY_B64 }}
        export_default_credentials: true
    - name: npm test
      run: npm run test
      working-directory: ./deploy-cloud-functions
      env:
        DEPLOY_CF_SA_KEY_JSON: ${{ secrets.DEPLOY_CF_SA_KEY_JSON }}
        GCLOUD_PROJECT: ${{ secrets.DEPLOY_CF_PROJECT_ID }}
        DEPLOY_CF_EVENT_PUBSUB_TOPIC: ${{ secrets.DEPLOY_CF_EVENT_PUBSUB_TOPIC }}