name: get-secretmanager-secrets Integration

on:
  push:
    paths:
    - 'get-secretmanager-secrets/**'
    - '.github/workflows/get-secretmanager-secrets*'


jobs:
  gcloud:
    name: with setup-gcloud
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GET_SECRETMANAGER_SECRETS_SA_KEY_B64 }}
        export_default_credentials: true
    - id: build
      name: Build dist
      working-directory: get-secretmanager-secrets
      run: |-
        npm install
        npm run build
    - id: secrets
      name: get secrets
      uses: ./get-secretmanager-secrets
      with:
        secrets: |-
          token:${{ secrets.GET_SECRETMANAGER_SECRETS_SECRET_REF }}
          password:${{ secrets.GET_SECRETMANAGER_SECRETS_SECRET_VERSION_REF }}
    - name: get output
      run: echo '${{ steps.secrets.outputs.token }}${{ steps.secrets.outputs.password }}'

  b64_json:
    name: with base64 json creds
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: build
      name: Build dist
      working-directory: get-secretmanager-secrets
      run: |-
        npm install
        npm run build
    - id: secrets
      name: get secrets
      uses: ./get-secretmanager-secrets
      with:
        credentials: ${{ secrets.GET_SECRETMANAGER_SECRETS_SA_KEY_JSON }}
        secrets: |-
          token:${{ secrets.GET_SECRETMANAGER_SECRETS_SECRET_REF }}
          password:${{ secrets.GET_SECRETMANAGER_SECRETS_SECRET_VERSION_REF }}
    - name: get output
      run: echo '${{ steps.secrets.outputs.token }}${{ steps.secrets.outputs.password }}'

  json:
    name: with json creds
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: build
      name: Build dist
      working-directory: get-secretmanager-secrets
      run: |-
        npm install
        npm run build
    - id: secrets
      name: get secrets
      uses: ./get-secretmanager-secrets
      with:
        credentials: ${{ secrets.GET_SECRETMANAGER_SECRETS_SA_KEY_JSON }}
        secrets: |-
          token:${{ secrets.GET_SECRETMANAGER_SECRETS_SECRET_REF }}
          password:${{ secrets.GET_SECRETMANAGER_SECRETS_SECRET_VERSION_REF }}
    - name: get output
      run: echo '${{ steps.secrets.outputs.token }}${{ steps.secrets.outputs.password }}'
