name: get-gke-credentials Unit

on:
  push:
    paths:
    - 'get-gke-credentials/**'
    - '.github/workflows/get-gke-credentials**'
  pull_request:
    paths:
    - 'get-gke-credentials/**'
    - '.github/workflows/get-gke-credentials**'

jobs:
  run:
    name: test
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@master
      with:
        node-version: 12.x

    - name: npm install
      run: npm install
      working-directory: ./get-gke-credentials

    - name: npm lint
      run: npm run lint
      working-directory: ./get-gke-credentials

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GET_GKE_CRED_SA_KEY_JSON }}
        export_default_credentials: true
    - name: npm test
      run: npm run test
      working-directory: ./get-gke-credentials
      env:
        GET_GKE_CRED_SA_KEY_JSON: ${{ secrets.GET_GKE_CRED_SA_KEY_JSON }}
        GET_GKE_CRED_PROJECT: ${{ secrets.GET_GKE_CRED_PROJECT }}
        GET_GKE_CRED_CLUSTER_NAME: ${{ secrets.GET_GKE_CRED_CLUSTER_NAME }}
        GKE_AUTH_CLUSTER_LOCATION: ${{ secrets.GKE_AUTH_CLUSTER_LOCATION }}
