on:
  push:
    branches:
      - master
name: build and release-please
env:
  ACTION_NAME: setup-gcloud
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        max-parallel: 1
        matrix: 
          actions: ["setupGcloudSDK", "setup-gcloud"]
    steps:
      - uses: actions/checkout@v2
      - run: git pull
      - name: install
        working-directory: ${{ matrix.actions }}
        run: npm install
      - name: build
        run: npm run build
        working-directory: ${{ matrix.actions }}
      - name: commit
        working-directory: ${{ matrix.actions }}
        run: |-
          set -e
          # get current commit hash
          CURRENT_HASH=$(git rev-parse HEAD)
          # get last commit hash of last build dist
          LAST_BUILD_HASH=$(git log --author=google-github-actions-bot -1 --pretty=format:"%H")
          DIFF=""
          # build and commit dist if diff
          git config --global user.name "actions-bot"
          git config user.email 'github-actions-bot@google.com'
          git add dist/
          git diff-index --quiet HEAD || git commit -m "chore: build dist ${{ matrix.actions }}"
          # if last commit hash of last build dist was found, get logs of commits in btw for PR body
          if [ -z "$LAST_BUILD_HASH" ]
          then
                echo "Unable to find last commit by bot, skipping diff gen"
          else
                DIFF=$(git log ${LAST_BUILD_HASH}...${CURRENT_HASH} --oneline)
                echo $DIFF
          fi
          # set env vars
          echo "CURRENT_HASH=${CURRENT_HASH}" >> $GITHUB_ENV
          echo "LAST_BUILD_HASH=${LAST_BUILD_HASH}" >> $GITHUB_ENV
          echo 'DIFF<<EOF' >> $GITHUB_ENV
          echo "${DIFF}" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          commit-message: Build dist
          author: "actions-bot <github-actions-bot@google.com>"
          title: "chore: build dist ${{ matrix.actions }}"
          body: |
            Build dist PR
            ${{env.DIFF}}
          labels: automated pr
          branch: create-pull-request/build-dist-${{ matrix.actions }}
          delete-branch: true
          push-to-fork: google-github-actions-bot/setup-gcloud
  release-please-pr:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: GoogleCloudPlatform/release-please-action@main
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          release-type: node
          bump-minor-pre-major: true
          fork: true
          package-name: ${{env.ACTION_NAME}}
          path: ${{env.ACTION_NAME}}
          command: release-pr
  release-please-release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: GoogleCloudPlatform/release-please-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          bump-minor-pre-major: true
          package-name: ${{env.ACTION_NAME}}
          path: ${{env.ACTION_NAME}}
          command: github-release
