name: setupGcloudSDK Unit
on: [push, pull_request]
jobs:
  run:
    name: setupGcloudSDK
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@master
      with:
        node-version: 12.x

    - name: npm install
      working-directory: ./setupGcloudSDK
      run: npm install

    - name: Lint
      working-directory: ./setupGcloudSDK
      run: npm run lint

    - name: Unit tests
      working-directory: ./setupGcloudSDK
      run: npm test